[manifest]

version = "1.0.0"

priority = 0

[[patches]]

[patches.pattern]

target = "card.lua"

pattern = "-- TARGET: get_chip_x_mult"

position = "before"

payload = '''
    if self.config.center == G.P_CENTERS.m_glass and G.jokers then
        if next(SMODS.find_card('j_glass')) then
            ret = 3
        end
    end
'''

match_indent = true