[manifest]
version = "1.0.0"
dump_lua = true
priority = 0

[[patches]]
[patches.pattern]
target = "functions/UI_definitions.lua"
pattern = "function create_UIBox_blind_tag(blind_choice, run_info)"
position = "after"
payload = "do return nil end"
match_indent = true